#!/sbin/bash
#!/bin/bash
#setup
rm -rf /root/autokonek
mkdir /root/autokonek
cd /root/autokonek

#download
wget https://raw.githubusercontent.com/senowahyu62/Auto-Reconnect-Xderm-Mini/main/core
wget https://raw.githubusercontent.com/senowahyu62/Auto-Reconnect-Xderm-Mini/main/init
wget https://raw.githubusercontent.com/senowahyu62/Auto-Reconnect-Xderm-Mini/main/post

#chmod
chmod +x /root/autokonek/core
chmod +x /root/autokonek/init
chmod +x /root/autokonek/post

#crontab
cron=$(ls /etc/crontabs/)
echo "5 0 * * * /root/autokonek/init">>/etc/crontabs/$cron
cat /etc/crontabs/$cron                                               
#done
